version: '3'

services:
  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    container_name: 'api-MySQL'
    restart: on-failure
    volumes:
      - mySqlData:/var/lib/mysql
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: api

volumes:
  mySqlData:
    name: mySqlData
